import bcrypt from 'bcryptjs';
import type {State,Organization,Role,Surplus} from '../types.js';
const iso=(d:Date)=>d.toISOString();
export async function seedData():Promise<State>{
 const now=new Date();const hash=await bcrypt.hash('FoodWise@2026',12);
 const org=(id:string,name:string,type:Role,more:Partial<Organization>={}):Organization=>({id,name,type,subtype:type==='INSTITUTION'?'Institutional kitchen':type==='RECIPIENT'?'Community shelter':'Delivery partner',address:'Shivamogga, Karnataka',verified:true,active:true,available:true,afterHours:false,capacity:250,requirement:100,dietary:['Vegetarian'],categories:['Cooked meals','Produce','Packaged food'],pickup:false,refrigeration:true,distance:2.4,openHour:0,closeHour:24,buffer:4,vehicle:'Insulated van',phone:'',...more});
 const organizations=[org('inst-1','Green Valley Kitchen','INSTITUTION'),org('inst-2','Lakeside Hostel Mess','INSTITUTION'),org('inst-3','Harvest Processing Unit','INSTITUTION'),org('rec-1','Annapurna Community Kitchen','RECIPIENT'),org('rec-2','Asha Food Bank','RECIPIENT',{distance:4.8,capacity:180,requirement:85,pickup:true}),org('rec-3','Night Shelter Alpha','RECIPIENT',{afterHours:true,distance:3.8,capacity:160,requirement:70}),org('rec-4','Sahaya Shelter','RECIPIENT',{available:false,distance:1.5}),org('rec-5','Little Steps Kitchen','RECIPIENT',{capacity:12,requirement:10,distance:3}),org('rec-6','Community Meal Centre','RECIPIENT',{dietary:['Non-vegetarian'],distance:5.1}),org('log-1','GreenRoute Logistics','LOGISTICS'),org('log-2','City Food Rescue','LOGISTICS',{available:false}),org('log-3','Community Fleet','LOGISTICS',{distance:6}),org('admin','FoodWise Network','ADMIN')];
 const users=([['admin','ADMIN','admin'],['institution','INSTITUTION','inst-1'],['recipient','RECIPIENT','rec-1'],['logistics','LOGISTICS','log-1'],['night','RECIPIENT','rec-3']] as [string,Role,string][]).map(([n,role,organizationId])=>({id:`user-${n}`,email:`${n}@foodwise.demo`,passwordHash:hash,name:n==='institution'?'Kitchen Manager':n.charAt(0).toUpperCase()+n.slice(1),role,organizationId,active:true}));
 const state:State={users,organizations,inventory:[],events:[],production:[],pos:[],imports:[],forecasts:[],surplus:[],notifications:[],audit:[],recovery:[],reports:[],settings:{kgPerServing:0.4,co2PerKg:2.5,costPerKg:80,minimumWindowMinutes:30,pickupDelayMinutes:15}};
 const items=['Veg Thali','Paneer Meal','Rice Bowl','Idli & Sambar','Dal Khichdi'];
 for(let d=210;d>=1;d--){const date=new Date(now);date.setUTCDate(date.getUTCDate()-d);const day=iso(date).slice(0,10);items.forEach((item,i)=>{const q=Math.round([174,72,110,130,85][i]*(1+0.13*Math.sin(d/7)+0.07*Math.cos(d*1.7+i))+(date.getUTCDay()===5?16:0));state.pos.push({id:`pos-${d}-${i}`,transactionId:`SYN-${day}-${i}`,organizationId:'inst-1',createdAt:iso(date),date:day,itemName:item,quantitySold:q,mealType:i===3?'Breakfast':'Lunch',unitPrice:[80,120,60,40,65][i],source:'Synthetic daily POS aggregate'});if(d<=30){const prepared=q+Math.round(6+Math.abs(Math.sin(d+i))*12);state.production.push({id:`prod-${d}-${i}`,organizationId:'inst-1',createdAt:iso(date),date:day,itemName:item,prepared,consumed:q,surplus:prepared-q,unit:'servings',baseline:prepared+10,source:'Synthetic history'});}});}
 const stocks=[['Basmati rice',140,30,90,'Dry store'],['Fresh paneer',8,12,2,'Cold storage'],['Tomatoes',24,10,1,'Produce room'],['Toor dal',65,20,120,'Dry store'],['Cooking oil',38,15,180,'Dry store'],['Yogurt',0,10,-1,'Cold storage']];
 stocks.forEach(([item,quantity,min,days,storage],i)=>state.inventory.push({id:`inv-${i}`,organizationId:'inst-1',createdAt:iso(now),itemName:item,quantity,unit:i===4?'liters':'kg',minimum:min,expiry:iso(new Date(+now+Number(days)*86400000)).slice(0,10),storage,batch:`GV-26-${i+1}`,category:i<2?'Ingredients':'Produce'}));
 for(let d=1;d<=24;d++){const date=new Date(+now-d*86400000);const qty=24+d%7*4;const s:Surplus={id:`history-${d}`,organizationId:d%5===0?'inst-2':'inst-1',createdAt:iso(date),foodName:items[d%5],category:'Cooked meals',dietaryType:'Vegetarian',quantity:qty,unit:'servings',servings:qty,preparedAt:iso(date),detectedAt:iso(date),availableUntil:iso(new Date(+date+7200000)),storageMethod:'Hot held',temperature:65,packagingStatus:'Sealed',declaration:true,contaminated:false,organic:true,status:d%7===0?'expired':'completed',assessment:'potentially suitable',assessmentReasons:['Synthetic history; institution handling declaration recorded'],afterHours:d%6===0,recipientId:d%6===0?'rec-3':'rec-1',partnerId:'log-1',pickupMode:'delivery',receivedQuantity:qty,timeline:[{at:iso(date),action:'Synthetic redistribution record',actor:'Demo seed'}]};state.surplus.push(s);}
 state.recovery.push({id:'recovery-seed',organizationId:'inst-1',createdAt:iso(now),foodName:'Vegetable trimmings',quantity:18,unit:'kg',method:'Composting',partner:'Green Loop Recovery (simulated)',reason:'Preparation by-products; not for human redistribution',status:'completed'});
 state.notifications.push({id:'welcome',organizationId:'inst-1',createdAt:iso(now),title:'Your kitchen workspace is ready',message:'Explore 210 days of synthetic POS data and run your first forecast.',read:false,path:'/forecast',channel:'in-app'});
 return state;
}
