import {useState,type ReactNode} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import * as Select from '@radix-ui/react-select';
import {X,ChevronDown,Check,Search,ChevronLeft,ChevronRight,Inbox,Loader2} from 'lucide-react';
export type DataRow=Record<string,any>;
export function Badge({children,tone}:{children:ReactNode;tone?:string}){const s=String(children).toLowerCase();const color=tone||( /completed|healthy|verified|potentially suitable|connected|sealed/.test(s)?'green':/expired|not recommended|disposed|rejected|error/.test(s)?'red':/review|low|near expiry|offered|attention/.test(s)?'amber':/transit|assigned|after.hours|delivery/.test(s)?'blue':'neutral');return <span className={'badge '+color}>{children}</span>}
export function Button({children,onClick,kind='',disabled=false,type='button',className=''}:{children:ReactNode;onClick?:()=>void;kind?:string;disabled?:boolean;type?:'button'|'submit';className?:string}){return <button type={type} disabled={disabled} onClick={onClick} className={`button ${kind} ${className}`}>{children}</button>}
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label?:string}){return <Select.Root value={value} onValueChange={onChange}><Select.Trigger className="choice" aria-label={label||'Select option'}><Select.Value/><Select.Icon><ChevronDown size={15}/></Select.Icon></Select.Trigger><Select.Portal><Select.Content className="select-content" position="popper" sideOffset={5}><Select.Viewport>{options.map(o=><Select.Item key={o} value={o} className="select-item"><Select.ItemText>{o}</Select.ItemText><Select.ItemIndicator><Check size={14}/></Select.ItemIndicator></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal></Select.Root>}
export function Empty({title='Nothing here yet',text='New records will appear here as your workspace grows.',action}:{title?:string;text?:string;action?:ReactNode}){return <div className="empty"><span><Inbox size={28}/></span><h3>{title}</h3><p>{text}</p>{action}</div>}
export function Loading(){return <div className="loading"><Loader2 className="spin"/> Loading your workspace…</div>}
export function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode}){return <Dialog.Root open={open} onOpenChange={v=>{if(!v)onClose()}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="modal"><div className="modal-head"><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description||'Review the details before saving.'}</Dialog.Description></div><Dialog.Close className="icon-button" aria-label="Close"><X size={20}/></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export type Field={key:string;label:string;type?:string;options?:string[];value?:unknown;required?:boolean;min?:number;max?:number;help?:string};
export function FormModal({title,fields,onClose,onSave}:{title:string;fields:Field[];onClose:()=>void;onSave:(v:DataRow)=>Promise<void>}){const [values,setValues]=useState<DataRow>(Object.fromEntries(fields.map(f=>[f.key,f.value??(f.type==='checkbox'?false:f.options?.[0]??'')])));const [error,setError]=useState('');const [busy,setBusy]=useState(false);return <Modal open title={title} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result={...values};for(const f of fields){if(f.type==='number')result[f.key]=result[f.key]===''?undefined:Number(result[f.key]);if(f.type==='datetime-local')result[f.key]=new Date(String(result[f.key])).toISOString();}await onSave(result);onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false)}}}><div className="form-grid">{fields.map(f=><label key={f.key} className={f.type==='checkbox'?'check-field':f.type==='textarea'?'wide':''}>{f.type==='checkbox'?<><input type="checkbox" checked={Boolean(values[f.key])} onChange={e=>setValues({...values,[f.key]:e.target.checked})}/><span>{f.label}</span></>:<><span>{f.label}</span>{f.options?<Choice value={String(values[f.key])} options={f.options} label={f.label} onChange={v=>setValues({...values,[f.key]:v})}/>:f.type==='textarea'?<textarea value={values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>:<input type={f.type||'text'} required={f.required!==false} value={values[f.key]} min={f.min??(f.type==='number'?0:undefined)} max={f.max} step={f.type==='number'?'any':undefined} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>}</>}{f.help&&<small>{f.help}</small>}</label>)}</div>{error&&<div role="alert" className="error">{error}</div>}<div className="modal-actions"><Button kind="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy?<><Loader2 size={16} className="spin"/> Saving…</>:'Save changes'}</Button></div></form></Modal>}
export type Column={key:string;label:string;render?:(r:DataRow)=>ReactNode};
export function Table({rows,columns,empty,actions,search=true}:{rows:DataRow[];columns:Column[];empty?:string;actions?:ReactNode;search?:boolean}){const [q,setQ]=useState('');const [page,setPage]=useState(1);const [sort,setSort]=useState('');const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase()));const sorted=sort?[...filtered].sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''),undefined,{numeric:true})):filtered;const pages=Math.max(1,Math.ceil(sorted.length/8));const p=Math.min(page,pages);return <div className="table-wrap">{(search||actions)&&<div className="table-tools">{search&&<div className="search-field"><Search size={17}/><input aria-label="Search records" placeholder="Search records…" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></div>}<div>{actions}</div></div>}{!sorted.length?<Empty title={empty||'No matching records'} text="Try another filter or add a new record."/>:<><div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c.key}><button onClick={()=>setSort(c.key)}>{c.label}</button></th>)}</tr></thead><tbody>{sorted.slice((p-1)*8,p*8).map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):String(r[c.key]??'—')}</td>)}</tr>)}</tbody></table></div><div className="pagination"><span>{(p-1)*8+1}–{Math.min(p*8,sorted.length)} of {sorted.length} records</span><div><button aria-label="Previous page" disabled={p===1} onClick={()=>setPage(p-1)}><ChevronLeft size={16}/></button><span>{p} / {pages}</span><button aria-label="Next page" disabled={p===pages} onClick={()=>setPage(p+1)}><ChevronRight size={16}/></button></div></div></>}</div>}
export function Panel({title,sub,action,children,className=''}:{title:string;sub?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={'panel '+className}><div className="panel-head"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>{children}</section>}
export const number=(x:unknown)=>Number(x||0).toLocaleString('en-IN',{maximumFractionDigits:1});
export const time=(x:unknown)=>x?new Date(String(x)).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
export const day=(offset=0)=>new Date(Date.now()+offset*86400000).toISOString().slice(0,10);
export const localDate=(offset=0)=>{const d=new Date(Date.now()+offset*60000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
